### ISSUE TITLE
Not able to see file type icons in boxy theme ocean

### ISSUE THREAD

**Issue by nitish24p** [oivva/sublime-boxy#147]
Not a hindering issue but initially i was able to see file type icons  depending on the file type eg .js, .php. Now its been replaced by </>.
<img width="168" alt="screen shot 2016-11-15 at 6 02 50 pm" src="https://cloud.githubusercontent.com/assets/13037986/20305920/f29cbae2-ab5d-11e6-80b7-03125f5b6d7a.png">

**Comment by oivva** [comment]
Please install [zz File Icons](https://packagecontrol.io/packages/zz%20File%20Icons) package.

**Comment by nitish24p** [comment]
Thanks
